env:
  es2021: true,
  node: true
extends:
  - airbnb-base
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  allowImportExportEverywhere: true
rules:
  import/extensions: 0
  no-param-reassign: 0
  func-names: 0
